import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { createServer } from "node:net";
import { accessSync, constants, readFileSync } from "node:fs";
import test from "node:test";

const root = new URL("..", import.meta.url).pathname;
const freePort = () => new Promise((resolve, reject) => { const server = createServer(); server.once("error", reject); server.listen(0, "127.0.0.1", () => { const port = server.address().port; server.close(() => resolve(port)); }); });
const waitFor = async (url) => { const deadline = Date.now() + 10_000; while (Date.now() < deadline) { try { const result = await fetch(url); if (result.ok) return result; } catch {} await new Promise((resolve) => setTimeout(resolve, 80)); } throw new Error(`Timed out: ${url}`); };

test("standalone 1helm.com website serves independent product and documentation surface", async () => {
  const port = await freePort();
  const child = spawn(process.execPath, ["site/server.mjs"], { cwd: root, env: { ...process.env, SITE_PORT: String(port) }, stdio: ["ignore", "pipe", "pipe"] });
  try {
    const base = `http://127.0.0.1:${port}`;
    const health = await (await waitFor(`${base}/health`)).json();
    assert.equal(health.surface, "website");
    const home = await (await fetch(base)).text();
    assert.match(home, /Welcome to/);
    assert.match(home, /Intelligence should not be/);
    assert.match(home, /skip to the end/);
    assert.doesNotMatch(home, /signed-source metadata/);
    assert.doesNotMatch(home, /style="/);
    const manual = await (await fetch(`${base}/manual`)).text();
    assert.match(manual, /The Ship's/);
    assert.match(manual, /Do I really need a dedicated computer/);
    const privacy = await (await fetch(`${base}/privacy`)).text();
    assert.match(privacy, /build@1helm\.com/);
    assert.match(home, /build@1helm\.com/);
    assert.match(home, /og:image/);
    assert.match(home, /assets\/story\/og-card\.png/);
    for (const path of ["/manual", "/terms", "/privacy", "/product", "/manifesto", "/security", "/faq", "/docs", "/docs/install/macos", "/docs/install/linux", "/docs/install/windows-wsl", "/docs/skills", "/docs/verification", "/docs/connections"]) {
      const response = await fetch(base + path); assert.equal(response.status, 200, path);
      assert.match(response.headers.get("content-security-policy") || "", /default-src 'self'/);
    }
    const gettingStarted = await (await fetch(`${base}/docs/getting-started`)).text();
    assert.match(gettingStarted, /On Windows 11 x64, download the signed Setup executable/i);
    assert.doesNotMatch(gettingStarted, /withheld/i);
    assert.equal((await fetch(`${base}/assets/site.css`)).status, 200);
    const windowsIcon = await fetch(`${base}/icons/icon-sailboat.ico`);
    assert.equal(windowsIcon.status, 200);
    assert.equal(windowsIcon.headers.get("content-type"), "image/x-icon");
    const benchmarkSchema = await (await fetch(`${base}/schemas/autonomy-benchmark-v1.json`)).json();
    assert.equal(benchmarkSchema.$id, "https://1helm.com/schemas/autonomy-benchmark-v1.json");
    assert.deepEqual(benchmarkSchema.required, ["schema", "product", "kind", "started_at", "finished_at", "deterministic", "scope", "summary", "checks"]);
    assert.equal((await fetch(`${base}/install.sh`)).status, 200);
    assert.equal((await fetch(`${base}/../../package.json`)).status, 404);
    const sitemap = await (await fetch(`${base}/sitemap.xml`)).text();
    assert.match(sitemap, /https:\/\/1helm\.com\/docs\/connections/);
    const download = await fetch(`${base}/download/macos`, { redirect: "manual" });
    assert.equal(download.status, 302);
    assert.match(download.headers.get("location") || "", /1Helm-[\d.]+-arm64\.dmg$|\/releases\/latest$/);
    const windowsDownload = await fetch(`${base}/download/windows`, { redirect: "manual" });
    assert.equal(windowsDownload.status, 302);
    assert.match(windowsDownload.headers.get("location") || "", /-windows-x64-setup\.exe$|\/releases\/latest$/);
  } finally { child.kill("SIGTERM"); await new Promise((resolve) => child.once("exit", resolve)); }
});

test("installer assets are explicit and syntax-valid", () => {
  accessSync(`${root}/site/public/install.sh`, constants.R_OK);
  const installer = readFileSync(`${root}/site/public/install.sh`, "utf8");
  assert.match(installer, /install-lxc-runtime\.sh/, "the host installer provisions the root-owned runtime boundary");
  assert.match(installer, /install-linux-units\.sh/, "fresh installs use the shared Linux service contract");
  assert.match(installer, /snapshot_host_contract[\s\S]*rollback_host_contract[\s\S]*TRANSACTION_ACTIVE/, "fresh and repeat installs restore runtime files and unit state after any transactional failure");
  assert.match(installer, /rollback_host_contract[\s\S]*1helm\.service\.active[\s\S]*api\/setup\/status[\s\S]*restored_healthy/, "installer rollback verifies the restored service before claiming recovery");
  assert.match(installer, /NODE_VERSION="22\.23\.1"/);
  assert.match(installer, /need=\([^\n]*flock[^\n]*make[^\n]*c\+\+[^\n]*python3[^\n]*\)/, "the host updater and native dependency toolchain are probed even when download prerequisites already exist");
  assert.match(installer, /import ensurepip[\s\S]*python3-venv/, "the Linux host installs Python's venv support required by durable memory instead of accepting a python3 executable alone");
  assert.doesNotMatch(installer, /npm[^\n]*ci[^\n]*--omit=optional/, "platform-specific optional build packages are retained");
  assert.match(installer, /EXISTING_SHA="\$\(runuser -u "\$SERVICE_USER" -- git -C "\$RELEASE_ROOT" rev-parse HEAD/, "repeat installs inspect the service-owned release as the service user");
  assert.match(installer, /RELEASES_ROOT=.*releases/);
  assert.match(installer, /mv -Tf .*current/);
  assert.match(installer, /previous release was restored/i);
  assert.match(installer, /PREVIOUS_RELEASE[\s\S]*== "\$RELEASES_ROOT\/"\*[\s\S]*\{1\.\.300\}/, "fresh installs reject unsafe rollback links and allow a full minute for first-run runtime initialization");
  assert.match(installer, /1helm-update\.path/, "standard Linux installs watch the private host update request file");
  const updater = readFileSync(`${root}/site/public/update-host.sh`, "utf8");
  const linuxUnits = readFileSync(`${root}/site/public/install-linux-units.sh`, "utf8");
  assert.match(updater, /browser_download_url/);
  assert.match(updater, /\^sha256:\[a-f0-9\]\{64\}\$/, "the Linux updater requires GitHub's exact SHA-256 asset digest");
  assert.match(updater, /sha256sum -c -/);
  assert.match(updater, /mv -Tf .*current/);
  assert.match(updater, /previous release was restored/i);
  assert.match(updater, /VERSION_ORDER[\s\S]*Never downgrade[\s\S]*TARGET_VERSION="\$CURRENT_VERSION"/, "the root updater never replaces a newer installed host with an older latest-release response");
  assert.match(updater, /PREVIOUS_RELEASE[\s\S]*== "\$RELEASES_ROOT\/"\*[\s\S]*\{1\.\.300\}/, "updates reject unsafe rollback links and use the same bounded startup allowance");
  assert.match(updater, /\$RELEASE_ROOT\/site\/public\/install-lxc-runtime\.sh/, "the updater installs runtime files from the retained release after staging moves");
  assert.match(updater, /install-linux-units\.sh/, "updates migrate the host service contract instead of retaining an obsolete unit");
  assert.match(updater, /CURRENT_VERSION[\s\S]*HELM_CHANNEL_COMPUTER_BACKEND=lxc[\s\S]*application is current; the host is migrating its verified runtime contract/i, "an older updater can hand off same-version host-contract migration to the newly installed release");
  assert.match(updater, /\/etc\/subuid[\s\S]*snapshot_host_contract[\s\S]*rollback_host_contract[\s\S]*cleanup_transaction/, "updates transactionally restore identity maps, runtime files, symlink, and unit state");
  assert.doesNotMatch(updater, /eval|curl[^\n]*\|[^\n]*(?:sh|bash)/, "the root updater never evaluates remote shell content");
  const lxcInstaller = readFileSync(`${root}/site/public/install-lxc-runtime.sh`, "utf8");
  const hostMigration = readFileSync(`${root}/site/public/migrate-linux-host-contract.sh`, "utf8");
  const lxcHelper = readFileSync(`${root}/scripts/1helm-lxc-runtime`, "utf8");
  const lxcNetwork = readFileSync(`${root}/scripts/1helm-lxc-net`, "utf8");
  const lxcConfig = readFileSync(`${root}/deploy/1helm-lxc-unprivileged.conf`, "utf8");
  const uninstaller = readFileSync(`${root}/site/public/uninstall-host.sh`, "utf8");
  assert.match(lxcInstaller, /20260723_07:42/);
  assert.match(lxcInstaller, /cbc98489455ce54b5fa8c9abf276f1cb39130376ef70b3b7151d18362cd6354f/);
  assert.match(lxcInstaller, /f4752ea7e776f329f9f50aca59c1919f3dc841dc3ddf22beef2b1696c4b4e29e/);
  assert.match(lxcInstaller, /visudo -cf/, "the minimal helper-only sudo policy is validated before installation");
  assert.match(lxcInstaller, /apt-get install[\s\S]*python3-venv[\s\S]*lxc/, "0.0.5 upgrades can install the LXC and durable-memory prerequisites the older host did not have");
  assert.match(lxcInstaller, /namespace_covers_range[\s\S]*65536 65535/, "the installer negotiates a full bare-metal or safe nested-host subordinate ID range");
  assert.match(updater, /systemd-run[\s\S]*migrate-linux-host-contract\.sh/, "a verified transient root transaction migrates host files outside the older updater's read-only namespace");
  assert.match(hostMigration, /RELEASE_ROOT.*RELEASES_ROOT[\s\S]*snapshot_host_contract[\s\S]*rollback_host_contract[\s\S]*\{1\.\.300\}/, "the fixed host migration accepts only retained releases and rolls back the complete contract after a bounded health failure");
  assert.match(hostMigration, /rollback_host_contract[\s\S]*SERVICE_NAME\.active[\s\S]*api\/setup\/status[\s\S]*restored_healthy/, "rollback is not reported as complete until the restored service is HTTP-healthy");
  assert.doesNotMatch(hostMigration, /https?:\/\/(?!127\.0\.0\.1)|\beval\b|curl[^\n]*\|[^\n]*(?:sh|bash)/, "the privileged host migration never fetches or evaluates remote code");
  assert.match(lxcHelper, /ownership marker does not match/);
  assert.match(lxcHelper, /cleanup_incomplete_create[\s\S]*rm -rf -- "\$LXC_PATH\/\$name"[\s\S]*created=1[\s\S]*lxc-create/, "a failed create removes only its validated partial container directory");
  assert.match(lxcHelper, /cpuset\.cpus\.effective/, "LXC CPU limits are selected from the service's actually delegated host CPUs");
  assert.match(lxcHelper, /cpu_count/, "LXC inspection counts noncontiguous delegated CPU lists correctly");
  assert.match(lxcNetwork, /1helm-lxc-net-owned/, "the bridge wrapper stops only a bridge it started");
  assert.match(lxcNetwork, /1helm-lxc-net-rules-owned[\s\S]*table ip onehelm_lxc[\s\S]*masquerade/, "an adopted bridge receives a separately owned, removable outbound NAT contract");
  assert.match(lxcHelper, /nameserver 10\.0\.3\.1[\s\S]*apt-get update/, "new guests have bridge DNS before package bootstrap");
  assert.match(lxcConfig, /lxc\.apparmor\.profile = generated/);
  assert.match(lxcConfig, /lxc\.apparmor\.allow_nesting = 0/);
  assert.doesNotMatch(lxcConfig, /lxc\.mount\.entry|lxc\.mount\.auto[^\n]*home/, "the container config never maps a host home or application state");
  assert.match(uninstaller, /installation_id/);
  assert.match(uninstaller, /ctrl-pane\.db/, "Linux removal reads the real durable 1Helm database");
  assert.match(linuxUnits, /HELM_CHANNEL_COMPUTER_BACKEND=lxc/);
  assert.match(linuxUnits, /HELM_INSTALL_KIND=linux-systemd/, "standard Linux installs identify their host-owned update mechanism");
  assert.match(linuxUnits, /Delegate=yes/, "systemd delegates the service cgroup required for nested channel containers");
  assert.match(uninstaller, /"\$HELPER" delete "\$name" "\$INSTALLATION_ID:\$channel_id"/, "uninstall deletes only exact installation-owned containers");
  assert.match(uninstaller, /Preserved %s/, "uninstall preserves durable workspace state");
});

test("standalone deployment runs the website and tunnel without root process authority", () => {
  const siteUnit = readFileSync(`${root}/deploy/1helm-site.service`, "utf8");
  const tunnelUnit = readFileSync(`${root}/deploy/1helm-site-cloudflared.service`, "utf8");
  const tunnelConfig = readFileSync(`${root}/deploy/config-1helm-site.yml.example`, "utf8");
  assert.match(siteUnit, /DynamicUser=yes/);
  assert.match(siteUnit, /ProtectHome=yes/);
  assert.match(tunnelUnit, /DynamicUser=yes/);
  assert.match(tunnelUnit, /LoadCredential=1helm-site-tunnel\.json:\/etc\/cloudflared\/1helm-site-tunnel\.json/);
  assert.match(tunnelUnit, /tunnel run --credentials-file \$\{CREDENTIALS_DIRECTORY\}\/1helm-site-tunnel\.json/);
  assert.doesNotMatch(tunnelConfig, /^credentials-file:/m);
  assert.match(tunnelConfig, /127\.0\.0\.1:8130/);
});

test("autonomy report names its deterministic scope and live-system limits", () => {
  const report = JSON.parse(execFileSync(process.execPath, ["scripts/autonomy-benchmark.mjs"], { cwd: root, encoding: "utf8" }));
  assert.equal(report.schema, "https://1helm.com/schemas/autonomy-benchmark-v1.json");
  assert.equal(report.kind, "deterministic_runtime_contract");
  assert.equal(report.deterministic, true);
  assert.equal(report.summary.failed, 0);
  assert.match(report.scope.validates.join(" "), /wakeable recurring-work persistence/);
  assert.match(report.scope.does_not_validate.join(" "), /live model or provider/);
});
